const { Router } = require("express");
const dictionaryRoutes = require("./dictionary.routes");
const authorRoutes = require("./author.routes");
const categoryRoutes = require("./category.routes");
const descriptionRoutes = require("./description.routes");
const socialRoutes = require("./social.routes");
const authorSocialRoutes = require("./author_social.routes");
const topicRoutes = require("./topic.routes");
const tagRoutes = require("./tag.routes");
const mediaRoutes = require("./media.routes");
const desc_topicRoutes = require("./desc_topic.routes");
const question_answerRoutes = require("./question_answer.routes");
const synonimRoutes = require("./synonim.routes");
const desc_qaRoutes = require("./desc_qa.routes");
const adminRoutes = require("./admin.routes");
const userRoutes = require("./user.routes");
const router = Router();

router.use("/api/category", categoryRoutes);
router.use("/api/user", userRoutes);
router.use("/api/admin", adminRoutes);
router.use("/api/author", authorRoutes);
router.use("/api/dictionary", dictionaryRoutes);
router.use("/api/description", descriptionRoutes);
router.use("/api/social", socialRoutes);
router.use("/api/author_social", authorSocialRoutes);
router.use("/api/topic", topicRoutes);
router.use("/api/tag", tagRoutes);
router.use("/api/media", mediaRoutes);
router.use("/api/desc_topic", desc_topicRoutes);
router.use("/api/question_answer", question_answerRoutes);
router.use("/api/desc_qa", desc_qaRoutes);
router.use("/api/synonim", synonimRoutes);
module.exports = router;
